# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_multiplechoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_id',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='multiplechoice',
            name='correct_answer',
            field=models.CharField(default='A', max_length=255),
        ),
    ]
