# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_auto_20171120_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('exam_name', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=255)),
                ('question_picking', models.CharField(max_length=255)),
                ('availability', models.CharField(max_length=255)),
                ('start_date', models.CharField(max_length=255)),
                ('start_time', models.CharField(max_length=255)),
                ('end_date', models.CharField(max_length=255)),
                ('end_time', models.CharField(max_length=255)),
                ('candidates', models.CharField(max_length=255)),
                ('number_of_questions', models.IntegerField()),
                ('from_section', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='multiplechoice',
            options={'verbose_name': 'Multiple Choice Question', 'verbose_name_plural': 'Multiple Choice Questions'},
        ),
    ]
