# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 09:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0007_candidates'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Candidates',
        ),
    ]
