# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0009_candidates'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_id', models.CharField(max_length=255)),
                ('question_section', models.CharField(max_length=255)),
                ('user_id', models.CharField(max_length=255)),
                ('question_id', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Exam Question',
                'verbose_name_plural': 'Exam Questions',
            },
        ),
        migrations.AlterModelOptions(
            name='exam',
            options={'verbose_name': 'Exam', 'verbose_name_plural': 'Exams'},
        ),
        migrations.RemoveField(
            model_name='exam',
            name='from_section',
        ),
    ]
