# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 09:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0011_candidategroup_questionsection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidategroup',
            old_name='section_name',
            new_name='group_name',
        ),
    ]
