# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0013_auto_20171125_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidategroup',
            name='candidate_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questionsection',
            name='question_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
