# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0016_auto_20171125_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamQuestionSections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('exam_id', models.CharField(max_length=255)),
                ('question_section', models.CharField(max_length=255)),
                ('number_of_questions', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.RenameModel(
            old_name='ExamQuestions',
            new_name='ExamCandidateGroups',
        ),
        migrations.DeleteModel(
            name='ExamCandidates',
        ),
        migrations.RenameField(
            model_name='examcandidategroups',
            old_name='exam_question_id',
            new_name='group_section',
        ),
    ]
