# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 12:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0017_auto_20171125_1812'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examcandidategroups',
            options={'verbose_name': 'Exam Candidate Group', 'verbose_name_plural': 'Exam Candidate Groups'},
        ),
        migrations.AlterModelOptions(
            name='examquestionsections',
            options={'verbose_name': 'Exam Question Section', 'verbose_name_plural': 'Exam Question Sections'},
        ),
    ]
